sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t yuleetea/learndocker -f Dockerfile.dev .

script:
  - docker run -e CI=true yuleetea/learndocker npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'learndocker'
  env: 'Learndocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-373240450338'
  bucket_path: 'learndocker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
