sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t yuleetea/learndocker -f Dockerfile.dev .

script:
  - docker run -e CI=true yuleetea/learndocker npm run test
